# Generated by Django 3.2.7 on 2021-09-29 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('initreleasedate', models.DateField()),
                ('lastreleasedate', models.DateField()),
                ('devGroups', models.ManyToManyField(to='common.Group')),
                ('devPeople', models.ManyToManyField(to='common.Person')),
                ('predecessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predecessor_id', to='games.engine')),
                ('successor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successor_id', to='games.engine')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, null=True)),
                ('generation', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('releasedate', models.DateField()),
                ('discountdate', models.DateField(blank=True, null=True)),
                ('manufacturers', models.ManyToManyField(to='common.Group')),
                ('platformtype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.platformtype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('releasedate', models.DateField()),
                ('devGroups', models.ManyToManyField(related_name='devGroups', to='common.Group')),
                ('devPeople', models.ManyToManyField(to='common.Person')),
                ('engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engine', to='games.engine')),
                ('platforms', models.ManyToManyField(to='games.Platform')),
                ('publishers', models.ManyToManyField(related_name='publishers', to='common.Group')),
                ('tags', models.ManyToManyField(to='common.Tag')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
